import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Career Guidance System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Added suppressHydrationWarning to HTML tag
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Added suppressHydrationWarning to BODY tag
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}